services:
    message_broker:
        image: rabbitmq:management-alpine
        hostname: 'message_broker'
        ports:
            - "5672:5672"
            - "8080:15672"
        environment:
            - "RABBITMQ_DEFAULT_USER=${BROKER_USER}"
            - "RABBITMQ_DEFAULT_PASS=${BROKER_PASS}"
    state_storage:
        image: redis:latest
        ports:
            - "6379:6379"
    worker:
        image: celery_worker
        build: celery_worker
        environment:
            - "BROKER_USER=${BROKER_USER}"
            - "BROKER_PASS=${BROKER_PASS}"
            - "PROJECT_NAME=${PROJECT_NAME}"
